// import type { Metadata } from "next";
import { Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { GoogleTagManager } from "@next/third-parties/google";
import Script from "next/script";

const libre = Libre_Baskerville({ subsets: ["latin"], weight: ["400", "700"] });

// export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={libre.className}>
        <GoogleTagManager gtmId="GTM-5T54LP6N" />
        <Navbar />
        {children}

        <Footer />
      </body>
    </html>
  );
}
