import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
    return [
        {
            url: 'https://www.theloftexchange.com/',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 1,
        },
        {
            url: 'https://www.theloftexchange.com/california-real-estate-search',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.8,
        },
        {
            url: 'https://www.theloftexchange.com/lofts-condos',
            lastModified: new Date(),
            changeFrequency: 'weekly',
            priority: 0.8,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods',
            lastModified: new Date(),
            changeFrequency: 'yearly',
            priority: 0.8,
        },
        {
            url: 'https://www.theloftexchange.com/contact',
            lastModified: new Date(),
            changeFrequency: 'yearly',
            priority: 0.4,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/central-city-west',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/bunker-hill',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/financial-district',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park',
            lastModified: new Date(),
            changeFrequency: 'monthly',
            priority: 0.5,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/940-e-2nd-st-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/barker-block-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/beacon-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/biscuit-company-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/gallery-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/molino-street-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/toy-factory-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/arts-district/toy-warehouse-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/central-city-west/1100-wilshire-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/central-city-west/vero',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/957-fig',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/angeleno-heights-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/cathy-village-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/figueroa-terrace-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/figueroa-view-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/grand-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/chinatown/the-terrace',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/bunker-hill/bunker-hill-tower',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/bunker-hill/promenade-west',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/bunker-hill/the-promenade-condominiums',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district/eastern-columbia-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district/santee-village-cornell-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district/santee-village-eckardt-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district/santee-village-textile-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/fashion-district/the-tomahawk-building-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/financial-district/655-hope-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/financial-district/library-court-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/bartlett-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/douglas-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/el-dorado-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/higgins-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/the-singer-dtla',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/pan-american-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/perla-on-broadway',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/rowan-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/historic-core/sb-grand-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo/little-tokyo-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo/mura-condominiums',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo/savoy-condominiums',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo/teramachi',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/little-tokyo/tokyo-villa-condominiums',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/ten50-condos',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/elleven-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/evo-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/grand-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/luma-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/metropolis',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/ritz-carlton',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
        {
            url: 'https://www.theloftexchange.com/neighborhoods/south-park/sky-lofts',
            lastModified: new Date(),
            changeFrequency: 'daily',
            priority: 0.64,
        },
    ]
}